spring:
  datasource:
    url: jdbc:h2:mem:albumPhotoAPI
    driver-class-name: org.h2.Driver
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}

  h2.console.enabled: true

springdoc.api-docs.path: /api-docs
